name: portfolio_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  cloudinary_public: ^0.23.1
  image_picker: ^1.2.1
  syncfusion_flutter_pdf: ^24.1.41
  file_picker: ^8.0.0
  google_fonts: ^6.1.0
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
